# foundry.toml

[profile.default]
src = 'contracts'
out = ".foundry-artifacts"
cache_path = ".foundry-cache"
test = 'test-foundry'
libs = ["node_modules", "lib"]
show_progress = true

[fuzz]
seed = '0x3e8'

# Invariant testing profile
[invariant]
runs = 800
depth = 150
show_metrics = true
extra_output = ["storageLayout"]
fail_on_revert = true
# Enables guided fuzzing
corpus_dir = ".foundry-cache/invariant"
shrink_run_limit = 2000
show_solidity = true


[fmt]
ignore = ["contracts/hardhat-dependency-compiler/**/*.sol"]
multiline_func_header = "all" # Solidity recommended
single_line_statement_blocks = "multi"
