# cspell:words solcoverjs

name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    # TODO: remove when the interfaces package is published
    - name: Update the reference to interfaces
      run: |
        sed -i -e 's/git@github.com/git+https:\/\/${PERSONAL_ACCESS_TOKEN}@github.com/g' package.json
        cat package.json

    - name: Install project
      run: yarn install

    - name: Spell check
      run: yarn cspell

    - name: Lint
      run: yarn fullCheck

    - name: Slither
      uses: crytic/slither-action@v0.4.0
      with:
        ignore-compile: true
        node-version: ${{ matrix.node-version }}

    # - name: Test deployment
    #   run: ./scripts/test_deploy.sh

    # - name: Test upgrade
    #   env:
    #     NODE_VERSION: ${{ matrix.node-version }}
    #   run: ./scripts/test_upgrade.sh

    # - name: Test ABI generation
    #   run: npx hardhat run scripts/generateAbi.ts

    # - name: Run tests
    #   env:
    #     NODE_OPTIONS: --max-old-space-size=12288
    #   run: npx hardhat coverage --solcoverjs .solcover.js

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
